<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/11 23:34:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=an00027',
  'username' => 'an00027',
  'password' => '8nzYWZ,Nndx7M8sQ',
  'name' => 'doctrine',
)),);
