<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/11 23:34:42
sfConfig::add(array(
  'mod_kompetenzkategorien_enabled' => true,
  'mod_kompetenzkategorien_view_class' => 'sfPHP',
));
