<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/12 00:54:36
sfConfig::add(array(
  'mod_profilmerkliste_enabled' => true,
  'mod_profilmerkliste_view_class' => 'sfPHP',
));
