<?php

/**
 * AnfragenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnfragenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnfragenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Anfragen');
    }
}