<?php

/**
 * NiveausTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NiveausTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NiveausTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Niveaus');
    }
}