<?php

/**
 * ProfilMerklisteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProfilMerklisteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProfilMerklisteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProfilMerkliste');
    }
}