<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/10 20:13:31
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => 'profil/index',
  'app_dokumente_image_versions' => array (
  'thumbnail' => 
  array (
    'upload_dir' => 'thumbnails/',
    'upload_url' => 'thumbnails/',
    'max_width' => 80,
    'max_height' => 80,
  ),
),
));
