<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/10 20:13:31
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'student',
    ),
  ),
);
