<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/12 00:47:36
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'student',
    ),
  ),
);
