<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/12 00:47:36
sfConfig::add(array(
  'mod_verfuegbarkeit_enabled' => true,
  'mod_verfuegbarkeit_view_class' => 'sfPHP',
));
