<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/10 20:14:43
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'student',
    ),
  ),
);
