<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/21 15:43:28
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'student',
    ),
  ),
);
