<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/21 15:42:23
sfConfig::add(array(
  'mod_verfuegbarkeit_enabled' => true,
  'mod_verfuegbarkeit_view_class' => 'sfPHP',
));
