generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Profile
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          profile
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Profile
        display: [vornamen, nachname]
      filter:  ~
      form:    ~
      edit:    
        title: Profil bearbeiten
      new:     ~
