# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Ankerservices - Benutzeroberfläche für Unternehmen
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, frontend_company/frontend_company.css, smoothness/jquery-ui-1.8.4.custom.css, idletimeout.css]

  javascripts:    [jquery-1.6.4.min.js, jquery.tokeninput.js]

  has_layout:     true
  layout:         layout
