<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/10/10 21:13:40
sfConfig::add(array(
  'mod_profil_merkliste_enabled' => true,
  'mod_profil_merkliste_view_class' => 'sfPHP',
));
