<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/10/11 21:26:29
$this->security = array (
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'firmen',
  ),
);
