<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Kompetenzen', 'doctrine');

/**
 * BaseKompetenzen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kompetenz_id
 * @property string $bezeichnung
 * @property string $beschreibung
 * @property integer $kompetenz_kategorie_id
 * @property integer $aktiv
 * @property timestamp $letzte_aenderung
 * @property KompetenzKategorien $KompetenzKategorien
 * @property Doctrine_Collection $Niveaus
 * 
 * @method integer             getKompetenzId()            Returns the current record's "kompetenz_id" value
 * @method string              getBezeichnung()            Returns the current record's "bezeichnung" value
 * @method string              getBeschreibung()           Returns the current record's "beschreibung" value
 * @method integer             getKompetenzKategorieId()   Returns the current record's "kompetenz_kategorie_id" value
 * @method integer             getAktiv()                  Returns the current record's "aktiv" value
 * @method timestamp           getLetzteAenderung()        Returns the current record's "letzte_aenderung" value
 * @method KompetenzKategorien getKompetenzKategorien()    Returns the current record's "KompetenzKategorien" value
 * @method Doctrine_Collection getNiveaus()                Returns the current record's "Niveaus" collection
 * @method Kompetenzen         setKompetenzId()            Sets the current record's "kompetenz_id" value
 * @method Kompetenzen         setBezeichnung()            Sets the current record's "bezeichnung" value
 * @method Kompetenzen         setBeschreibung()           Sets the current record's "beschreibung" value
 * @method Kompetenzen         setKompetenzKategorieId()   Sets the current record's "kompetenz_kategorie_id" value
 * @method Kompetenzen         setAktiv()                  Sets the current record's "aktiv" value
 * @method Kompetenzen         setLetzteAenderung()        Sets the current record's "letzte_aenderung" value
 * @method Kompetenzen         setKompetenzKategorien()    Sets the current record's "KompetenzKategorien" value
 * @method Kompetenzen         setNiveaus()                Sets the current record's "Niveaus" collection
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKompetenzen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kompetenzen');
        $this->hasColumn('kompetenz_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bezeichnung', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('beschreibung', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('kompetenz_kategorie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('aktiv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 0,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('letzte_aenderung', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('KompetenzKategorien', array(
             'local' => 'kompetenz_kategorie_id',
             'foreign' => 'kompetenz_kategorie_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Niveaus', array(
             'local' => 'kompetenz_id',
             'foreign' => 'kompetenz_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'angelegt',
             ),
             'updated' => 
             array(
              'name' => 'letzte_aenderung',
             ),
             ));
        $this->actAs($timestampable0);
    }
}