<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Verfuegbarkeit', 'doctrine');

/**
 * BaseVerfuegbarkeit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $datum
 * @property integer $profil_id
 * @property integer $stundenzahl
 * @property text $zeitraum
 * @property string $anmerkung
 * @property Profile $Profile
 * 
 * @method date           getDatum()       Returns the current record's "datum" value
 * @method integer        getProfilId()    Returns the current record's "profil_id" value
 * @method integer        getStundenzahl() Returns the current record's "stundenzahl" value
 * @method text           getZeitraum()    Returns the current record's "zeitraum" value
 * @method string         getAnmerkung()   Returns the current record's "anmerkung" value
 * @method Profile        getProfile()     Returns the current record's "Profile" value
 * @method Verfuegbarkeit setDatum()       Sets the current record's "datum" value
 * @method Verfuegbarkeit setProfilId()    Sets the current record's "profil_id" value
 * @method Verfuegbarkeit setStundenzahl() Sets the current record's "stundenzahl" value
 * @method Verfuegbarkeit setZeitraum()    Sets the current record's "zeitraum" value
 * @method Verfuegbarkeit setAnmerkung()   Sets the current record's "anmerkung" value
 * @method Verfuegbarkeit setProfile()     Sets the current record's "Profile" value
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVerfuegbarkeit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('verfuegbarkeit');
        $this->hasColumn('datum', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('profil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('stundenzahl', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('zeitraum', 'text', null, array(
             'type' => 'text',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('anmerkung', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profil_id',
             'foreign' => 'profil_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}