<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Zertifikate', 'doctrine');

/**
 * BaseZertifikate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $zertifikat_id
 * @property string $bezeichnung
 * @property integer $profil_id
 * @property string $beschreibung
 * @property string $link
 * @property Profile $Profile
 * @property Doctrine_Collection $Niveaus
 * 
 * @method integer             getZertifikatId()  Returns the current record's "zertifikat_id" value
 * @method string              getBezeichnung()   Returns the current record's "bezeichnung" value
 * @method integer             getProfilId()      Returns the current record's "profil_id" value
 * @method string              getBeschreibung()  Returns the current record's "beschreibung" value
 * @method string              getLink()          Returns the current record's "link" value
 * @method Profile             getProfile()       Returns the current record's "Profile" value
 * @method Doctrine_Collection getNiveaus()       Returns the current record's "Niveaus" collection
 * @method Zertifikate         setZertifikatId()  Sets the current record's "zertifikat_id" value
 * @method Zertifikate         setBezeichnung()   Sets the current record's "bezeichnung" value
 * @method Zertifikate         setProfilId()      Sets the current record's "profil_id" value
 * @method Zertifikate         setBeschreibung()  Sets the current record's "beschreibung" value
 * @method Zertifikate         setLink()          Sets the current record's "link" value
 * @method Zertifikate         setProfile()       Sets the current record's "Profile" value
 * @method Zertifikate         setNiveaus()       Sets the current record's "Niveaus" collection
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZertifikate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zertifikate');
        $this->hasColumn('zertifikat_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bezeichnung', 'string', 75, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 75,
             ));
        $this->hasColumn('profil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('beschreibung', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Profile', array(
             'local' => 'profil_id',
             'foreign' => 'profil_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasMany('Niveaus', array(
             'local' => 'zertifikat_id',
             'foreign' => 'zertifikat_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}