<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('LebenslaufKategorien', 'doctrine');

/**
 * BaseLebenslaufKategorien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $art_id
 * @property string $bezeichnung
 * @property Doctrine_Collection $Lebenslauf
 * 
 * @method integer              getArtId()       Returns the current record's "art_id" value
 * @method string               getBezeichnung() Returns the current record's "bezeichnung" value
 * @method Doctrine_Collection  getLebenslauf()  Returns the current record's "Lebenslauf" collection
 * @method LebenslaufKategorien setArtId()       Sets the current record's "art_id" value
 * @method LebenslaufKategorien setBezeichnung() Sets the current record's "bezeichnung" value
 * @method LebenslaufKategorien setLebenslauf()  Sets the current record's "Lebenslauf" collection
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLebenslaufKategorien extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lebenslauf_kategorien');
        $this->hasColumn('art_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bezeichnung', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lebenslauf', array(
             'local' => 'art_id',
             'foreign' => 'art_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}