<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KompetenzKategorien', 'doctrine');

/**
 * BaseKompetenzKategorien
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kompetenz_kategorie_id
 * @property string $bezeichnung
 * @property string $beschreibung
 * @property integer $aktiv
 * @property Doctrine_Collection $Kompetenzen
 * 
 * @method integer             getKompetenzKategorieId()   Returns the current record's "kompetenz_kategorie_id" value
 * @method string              getBezeichnung()            Returns the current record's "bezeichnung" value
 * @method string              getBeschreibung()           Returns the current record's "beschreibung" value
 * @method integer             getAktiv()                  Returns the current record's "aktiv" value
 * @method Doctrine_Collection getKompetenzen()            Returns the current record's "Kompetenzen" collection
 * @method KompetenzKategorien setKompetenzKategorieId()   Sets the current record's "kompetenz_kategorie_id" value
 * @method KompetenzKategorien setBezeichnung()            Sets the current record's "bezeichnung" value
 * @method KompetenzKategorien setBeschreibung()           Sets the current record's "beschreibung" value
 * @method KompetenzKategorien setAktiv()                  Sets the current record's "aktiv" value
 * @method KompetenzKategorien setKompetenzen()            Sets the current record's "Kompetenzen" collection
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKompetenzKategorien extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kompetenz_kategorien');
        $this->hasColumn('kompetenz_kategorie_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bezeichnung', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('beschreibung', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('aktiv', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 0,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Kompetenzen', array(
             'local' => 'kompetenz_kategorie_id',
             'foreign' => 'kompetenz_kategorie_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $nestedset0 = new Doctrine_Template_NestedSet(array(
             'hasManyRoots' => true,
             ));
        $this->actAs($nestedset0);
    }
}