<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProfilMerkliste', 'doctrine');

/**
 * BaseProfilMerkliste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $merklisten_id
 * @property string $query
 * @property timestamp $angelegt
 * @property timestamp $letzte_aenderung
 * @property bigint $sf_guard_user_id
 * @property integer $profil_id
 * @property sfGuardUser $sfGuardUser
 * @property Profile $Profile
 * 
 * @method integer         getMerklistenId()     Returns the current record's "merklisten_id" value
 * @method string          getQuery()            Returns the current record's "query" value
 * @method timestamp       getAngelegt()         Returns the current record's "angelegt" value
 * @method timestamp       getLetzteAenderung()  Returns the current record's "letzte_aenderung" value
 * @method bigint          getSfGuardUserId()    Returns the current record's "sf_guard_user_id" value
 * @method integer         getProfilId()         Returns the current record's "profil_id" value
 * @method sfGuardUser     getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method Profile         getProfile()          Returns the current record's "Profile" value
 * @method ProfilMerkliste setMerklistenId()     Sets the current record's "merklisten_id" value
 * @method ProfilMerkliste setQuery()            Sets the current record's "query" value
 * @method ProfilMerkliste setAngelegt()         Sets the current record's "angelegt" value
 * @method ProfilMerkliste setLetzteAenderung()  Sets the current record's "letzte_aenderung" value
 * @method ProfilMerkliste setSfGuardUserId()    Sets the current record's "sf_guard_user_id" value
 * @method ProfilMerkliste setProfilId()         Sets the current record's "profil_id" value
 * @method ProfilMerkliste setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method ProfilMerkliste setProfile()          Sets the current record's "Profile" value
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfilMerkliste extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('profile_merkliste');
        $this->hasColumn('merklisten_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('query', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('angelegt', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('letzte_aenderung', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('sf_guard_user_id', 'bigint', 20, array(
             'type' => 'bigint',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('profil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $this->hasOne('Profile', array(
             'local' => 'profil_id',
             'foreign' => 'profil_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'angelegt',
             ),
             'updated' => 
             array(
              'name' => 'letzte_aenderung',
             ),
             ));
        $this->actAs($timestampable0);
    }
}