<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('KompetenzErworbenBei', 'doctrine');

/**
 * BaseKompetenzErworbenBei
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ll_id
 * @property integer $niveau_id
 * 
 * @method integer              getLlId()      Returns the current record's "ll_id" value
 * @method integer              getNiveauId()  Returns the current record's "niveau_id" value
 * @method KompetenzErworbenBei setLlId()      Sets the current record's "ll_id" value
 * @method KompetenzErworbenBei setNiveauId()  Sets the current record's "niveau_id" value
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKompetenzErworbenBei extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kompetenz_erworben_bei');
        $this->hasColumn('ll_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('niveau_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}