<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('OrteKompetenzerwerb', 'doctrine');

/**
 * BaseOrteKompetenzerwerb
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $erwerb_id
 * @property string $bezeichnung
 * @property Doctrine_Collection $Niveaus
 * 
 * @method integer             getErwerbId()    Returns the current record's "erwerb_id" value
 * @method string              getBezeichnung() Returns the current record's "bezeichnung" value
 * @method Doctrine_Collection getNiveaus()     Returns the current record's "Niveaus" collection
 * @method OrteKompetenzerwerb setErwerbId()    Sets the current record's "erwerb_id" value
 * @method OrteKompetenzerwerb setBezeichnung() Sets the current record's "bezeichnung" value
 * @method OrteKompetenzerwerb setNiveaus()     Sets the current record's "Niveaus" collection
 * 
 * @package    ankerservices
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOrteKompetenzerwerb extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orte_kompetenzerwerb');
        $this->hasColumn('erwerb_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('bezeichnung', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Niveaus', array(
             'local' => 'erwerb_id',
             'foreign' => 'erwerb_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}