# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Ankerservices - Oberfläche für Angestellte
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, frontend_employee/frontend_employee.css, smoothness/jquery-ui-1.8.4.custom.css, idletimeout.css, datePicker.css, ankerservicesPlugin/datepicker-fixed.css]

  javascripts:    [date.js, date_de.js, jquery-1.6.4.min.js, jquery-ui-1.8.4.custom.min.js, jquery.ui.datepicker-de.js, jquery.datePicker.js, jquery.datePickerMultiMonth.js]

  has_layout:     true
  layout:         layout
